### ISSUE TITLE
Declare an open source license

### ISSUE THREAD

**Issue by sr189** [gocardless/creditsafe-ruby#13]
Hi,

thanks for the gem. Unfortunately it doesn't provide a license (MIT, BSD, Apache, etc.). Is this by accident or on purpose?

Kind regards!

**Comment by timrogers** [comment]
@sr189 Let me look into this and get back to you as soon as I can :smile:

**Comment by timrogers** [comment]
This is now released under the MIT license as of #14 - it was just an accident 🙈! Hope the gem is useful.

**Comment by sr189** [comment]
Awesome, thanks a lot for your work!
